/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as SuperadminRouteRouteImport } from './routes/superadmin/route'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as EmpleadoRouteRouteImport } from './routes/empleado/route'
import { Route as AnalistaRouteRouteImport } from './routes/analista/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiendaIndexRouteImport } from './routes/tienda/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as EmpleadoIndexRouteImport } from './routes/empleado/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as AnalistaIndexRouteImport } from './routes/analista/index'
import { Route as TiendaComprasRouteImport } from './routes/tienda/compras'
import { Route as LoginEmpleadoRouteImport } from './routes/login/empleado'
import { Route as LoginClienteRouteImport } from './routes/login/cliente'
import { Route as ApiVentasRouteImport } from './routes/api/ventas'
import { Route as ApiProveedoresRouteImport } from './routes/api/proveedores'
import { Route as ApiProductosRouteImport } from './routes/api/productos'
import { Route as ApiEmpleadosRouteImport } from './routes/api/empleados'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as ApiClientesRouteImport } from './routes/api/clientes'
import { Route as ApiCategoriasRouteImport } from './routes/api/categorias'
import { Route as ApiVentasIdRouteImport } from './routes/api/ventas/$id'
import { Route as ApiUploadImagenRouteImport } from './routes/api/upload/imagen'
import { Route as ApiSetupStatusRouteImport } from './routes/api/setup/status'
import { Route as ApiSetupBootstrapRouteImport } from './routes/api/setup/bootstrap'
import { Route as ApiReportesVentasPorCategoriaRouteImport } from './routes/api/reportes/ventas-por-categoria'
import { Route as ApiReportesVentasDelDiaRouteImport } from './routes/api/reportes/ventas-del-dia'
import { Route as ApiReportesStockDisponibleRouteImport } from './routes/api/reportes/stock-disponible'
import { Route as ApiReportesProductosMasVendidosRouteImport } from './routes/api/reportes/productos-mas-vendidos'
import { Route as ApiReportesClientesFrecuentesRouteImport } from './routes/api/reportes/clientes-frecuentes'
import { Route as ApiProveedoresIdRouteImport } from './routes/api/proveedores/$id'
import { Route as ApiProductosIdRouteImport } from './routes/api/productos/$id'
import { Route as ApiEmpleadosUserIdRouteImport } from './routes/api/empleados/$userId'
import { Route as ApiClientesMeRouteImport } from './routes/api/clientes/me'
import { Route as ApiClientesIdRouteImport } from './routes/api/clientes/$id'
import { Route as ApiCategoriasIdRouteImport } from './routes/api/categorias/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SuperadminProductosEditarProductIdRouteImport } from './routes/superadmin/productos/editar/$productId'
import { Route as SuperadminProductosDesactivarProductIdRouteImport } from './routes/superadmin/productos/desactivar/$productId'
import { Route as SuperadminClientesEditarClienteIdRouteImport } from './routes/superadmin/clientes/editar/$clienteId'
import { Route as PortalProductosEditarProductIdRouteImport } from './routes/portal/productos/editar/$productId'
import { Route as PortalProductosDesactivarProductIdRouteImport } from './routes/portal/productos/desactivar/$productId'
import { Route as PortalClientesEditarClienteIdRouteImport } from './routes/portal/clientes/editar/$clienteId'
import { Route as EmpleadoProductosEditarProductIdRouteImport } from './routes/empleado/productos/editar/$productId'
import { Route as EmpleadoProductosDesactivarProductIdRouteImport } from './routes/empleado/productos/desactivar/$productId'
import { Route as EmpleadoClientesEditarClienteIdRouteImport } from './routes/empleado/clientes/editar/$clienteId'
import { Route as ApiClientesMeVentasRouteImport } from './routes/api/clientes/me/ventas'

const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRouteRoute = SuperadminRouteRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadoRouteRoute = EmpleadoRouteRouteImport.update({
  id: '/empleado',
  path: '/empleado',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaRouteRoute = AnalistaRouteRouteImport.update({
  id: '/analista',
  path: '/analista',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/tienda/',
  path: '/tienda/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRouteRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const EmpleadoIndexRoute = EmpleadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpleadoRouteRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaIndexRoute = AnalistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalistaRouteRoute,
} as any)
const TiendaComprasRoute = TiendaComprasRouteImport.update({
  id: '/tienda/compras',
  path: '/tienda/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmpleadoRoute = LoginEmpleadoRouteImport.update({
  id: '/empleado',
  path: '/empleado',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => LoginRouteRoute,
} as any)
const ApiVentasRoute = ApiVentasRouteImport.update({
  id: '/api/ventas',
  path: '/api/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProveedoresRoute = ApiProveedoresRouteImport.update({
  id: '/api/proveedores',
  path: '/api/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductosRoute = ApiProductosRouteImport.update({
  id: '/api/productos',
  path: '/api/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmpleadosRoute = ApiEmpleadosRouteImport.update({
  id: '/api/empleados',
  path: '/api/empleados',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientesRoute = ApiClientesRouteImport.update({
  id: '/api/clientes',
  path: '/api/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriasRoute = ApiCategoriasRouteImport.update({
  id: '/api/categorias',
  path: '/api/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVentasIdRoute = ApiVentasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVentasRoute,
} as any)
const ApiUploadImagenRoute = ApiUploadImagenRouteImport.update({
  id: '/api/upload/imagen',
  path: '/api/upload/imagen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupStatusRoute = ApiSetupStatusRouteImport.update({
  id: '/api/setup/status',
  path: '/api/setup/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSetupBootstrapRoute = ApiSetupBootstrapRouteImport.update({
  id: '/api/setup/bootstrap',
  path: '/api/setup/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportesVentasPorCategoriaRoute =
  ApiReportesVentasPorCategoriaRouteImport.update({
    id: '/api/reportes/ventas-por-categoria',
    path: '/api/reportes/ventas-por-categoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportesVentasDelDiaRoute = ApiReportesVentasDelDiaRouteImport.update({
  id: '/api/reportes/ventas-del-dia',
  path: '/api/reportes/ventas-del-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportesStockDisponibleRoute =
  ApiReportesStockDisponibleRouteImport.update({
    id: '/api/reportes/stock-disponible',
    path: '/api/reportes/stock-disponible',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportesProductosMasVendidosRoute =
  ApiReportesProductosMasVendidosRouteImport.update({
    id: '/api/reportes/productos-mas-vendidos',
    path: '/api/reportes/productos-mas-vendidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportesClientesFrecuentesRoute =
  ApiReportesClientesFrecuentesRouteImport.update({
    id: '/api/reportes/clientes-frecuentes',
    path: '/api/reportes/clientes-frecuentes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProveedoresIdRoute = ApiProveedoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProveedoresRoute,
} as any)
const ApiProductosIdRoute = ApiProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductosRoute,
} as any)
const ApiEmpleadosUserIdRoute = ApiEmpleadosUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiEmpleadosRoute,
} as any)
const ApiClientesMeRoute = ApiClientesMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiClientesRoute,
} as any)
const ApiClientesIdRoute = ApiClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientesRoute,
} as any)
const ApiCategoriasIdRoute = ApiCategoriasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCategoriasRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminProductosEditarProductIdRoute =
  SuperadminProductosEditarProductIdRouteImport.update({
    id: '/productos/editar/$productId',
    path: '/productos/editar/$productId',
    getParentRoute: () => SuperadminRouteRoute,
  } as any)
const SuperadminProductosDesactivarProductIdRoute =
  SuperadminProductosDesactivarProductIdRouteImport.update({
    id: '/productos/desactivar/$productId',
    path: '/productos/desactivar/$productId',
    getParentRoute: () => SuperadminRouteRoute,
  } as any)
const SuperadminClientesEditarClienteIdRoute =
  SuperadminClientesEditarClienteIdRouteImport.update({
    id: '/clientes/editar/$clienteId',
    path: '/clientes/editar/$clienteId',
    getParentRoute: () => SuperadminRouteRoute,
  } as any)
const PortalProductosEditarProductIdRoute =
  PortalProductosEditarProductIdRouteImport.update({
    id: '/productos/editar/$productId',
    path: '/productos/editar/$productId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalProductosDesactivarProductIdRoute =
  PortalProductosDesactivarProductIdRouteImport.update({
    id: '/productos/desactivar/$productId',
    path: '/productos/desactivar/$productId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalClientesEditarClienteIdRoute =
  PortalClientesEditarClienteIdRouteImport.update({
    id: '/clientes/editar/$clienteId',
    path: '/clientes/editar/$clienteId',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const EmpleadoProductosEditarProductIdRoute =
  EmpleadoProductosEditarProductIdRouteImport.update({
    id: '/productos/editar/$productId',
    path: '/productos/editar/$productId',
    getParentRoute: () => EmpleadoRouteRoute,
  } as any)
const EmpleadoProductosDesactivarProductIdRoute =
  EmpleadoProductosDesactivarProductIdRouteImport.update({
    id: '/productos/desactivar/$productId',
    path: '/productos/desactivar/$productId',
    getParentRoute: () => EmpleadoRouteRoute,
  } as any)
const EmpleadoClientesEditarClienteIdRoute =
  EmpleadoClientesEditarClienteIdRouteImport.update({
    id: '/clientes/editar/$clienteId',
    path: '/clientes/editar/$clienteId',
    getParentRoute: () => EmpleadoRouteRoute,
  } as any)
const ApiClientesMeVentasRoute = ApiClientesMeVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => ApiClientesMeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRouteRouteWithChildren
  '/empleado': typeof EmpleadoRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/caja': typeof CajaRoute
  '/api/categorias': typeof ApiCategoriasRouteWithChildren
  '/api/clientes': typeof ApiClientesRouteWithChildren
  '/api/docs': typeof ApiDocsRoute
  '/api/empleados': typeof ApiEmpleadosRouteWithChildren
  '/api/productos': typeof ApiProductosRouteWithChildren
  '/api/proveedores': typeof ApiProveedoresRouteWithChildren
  '/api/ventas': typeof ApiVentasRouteWithChildren
  '/login/cliente': typeof LoginClienteRoute
  '/login/empleado': typeof LoginEmpleadoRoute
  '/tienda/compras': typeof TiendaComprasRoute
  '/analista/': typeof AnalistaIndexRoute
  '/api/': typeof ApiIndexRoute
  '/empleado/': typeof EmpleadoIndexRoute
  '/login/': typeof LoginIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categorias/$id': typeof ApiCategoriasIdRoute
  '/api/clientes/$id': typeof ApiClientesIdRoute
  '/api/clientes/me': typeof ApiClientesMeRouteWithChildren
  '/api/empleados/$userId': typeof ApiEmpleadosUserIdRoute
  '/api/productos/$id': typeof ApiProductosIdRoute
  '/api/proveedores/$id': typeof ApiProveedoresIdRoute
  '/api/reportes/clientes-frecuentes': typeof ApiReportesClientesFrecuentesRoute
  '/api/reportes/productos-mas-vendidos': typeof ApiReportesProductosMasVendidosRoute
  '/api/reportes/stock-disponible': typeof ApiReportesStockDisponibleRoute
  '/api/reportes/ventas-del-dia': typeof ApiReportesVentasDelDiaRoute
  '/api/reportes/ventas-por-categoria': typeof ApiReportesVentasPorCategoriaRoute
  '/api/setup/bootstrap': typeof ApiSetupBootstrapRoute
  '/api/setup/status': typeof ApiSetupStatusRoute
  '/api/upload/imagen': typeof ApiUploadImagenRoute
  '/api/ventas/$id': typeof ApiVentasIdRoute
  '/api/clientes/me/ventas': typeof ApiClientesMeVentasRoute
  '/empleado/clientes/editar/$clienteId': typeof EmpleadoClientesEditarClienteIdRoute
  '/empleado/productos/desactivar/$productId': typeof EmpleadoProductosDesactivarProductIdRoute
  '/empleado/productos/editar/$productId': typeof EmpleadoProductosEditarProductIdRoute
  '/portal/clientes/editar/$clienteId': typeof PortalClientesEditarClienteIdRoute
  '/portal/productos/desactivar/$productId': typeof PortalProductosDesactivarProductIdRoute
  '/portal/productos/editar/$productId': typeof PortalProductosEditarProductIdRoute
  '/superadmin/clientes/editar/$clienteId': typeof SuperadminClientesEditarClienteIdRoute
  '/superadmin/productos/desactivar/$productId': typeof SuperadminProductosDesactivarProductIdRoute
  '/superadmin/productos/editar/$productId': typeof SuperadminProductosEditarProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/api/categorias': typeof ApiCategoriasRouteWithChildren
  '/api/clientes': typeof ApiClientesRouteWithChildren
  '/api/docs': typeof ApiDocsRoute
  '/api/empleados': typeof ApiEmpleadosRouteWithChildren
  '/api/productos': typeof ApiProductosRouteWithChildren
  '/api/proveedores': typeof ApiProveedoresRouteWithChildren
  '/api/ventas': typeof ApiVentasRouteWithChildren
  '/login/cliente': typeof LoginClienteRoute
  '/login/empleado': typeof LoginEmpleadoRoute
  '/tienda/compras': typeof TiendaComprasRoute
  '/analista': typeof AnalistaIndexRoute
  '/api': typeof ApiIndexRoute
  '/empleado': typeof EmpleadoIndexRoute
  '/login': typeof LoginIndexRoute
  '/portal': typeof PortalIndexRoute
  '/setup': typeof SetupIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/tienda': typeof TiendaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categorias/$id': typeof ApiCategoriasIdRoute
  '/api/clientes/$id': typeof ApiClientesIdRoute
  '/api/clientes/me': typeof ApiClientesMeRouteWithChildren
  '/api/empleados/$userId': typeof ApiEmpleadosUserIdRoute
  '/api/productos/$id': typeof ApiProductosIdRoute
  '/api/proveedores/$id': typeof ApiProveedoresIdRoute
  '/api/reportes/clientes-frecuentes': typeof ApiReportesClientesFrecuentesRoute
  '/api/reportes/productos-mas-vendidos': typeof ApiReportesProductosMasVendidosRoute
  '/api/reportes/stock-disponible': typeof ApiReportesStockDisponibleRoute
  '/api/reportes/ventas-del-dia': typeof ApiReportesVentasDelDiaRoute
  '/api/reportes/ventas-por-categoria': typeof ApiReportesVentasPorCategoriaRoute
  '/api/setup/bootstrap': typeof ApiSetupBootstrapRoute
  '/api/setup/status': typeof ApiSetupStatusRoute
  '/api/upload/imagen': typeof ApiUploadImagenRoute
  '/api/ventas/$id': typeof ApiVentasIdRoute
  '/api/clientes/me/ventas': typeof ApiClientesMeVentasRoute
  '/empleado/clientes/editar/$clienteId': typeof EmpleadoClientesEditarClienteIdRoute
  '/empleado/productos/desactivar/$productId': typeof EmpleadoProductosDesactivarProductIdRoute
  '/empleado/productos/editar/$productId': typeof EmpleadoProductosEditarProductIdRoute
  '/portal/clientes/editar/$clienteId': typeof PortalClientesEditarClienteIdRoute
  '/portal/productos/desactivar/$productId': typeof PortalProductosDesactivarProductIdRoute
  '/portal/productos/editar/$productId': typeof PortalProductosEditarProductIdRoute
  '/superadmin/clientes/editar/$clienteId': typeof SuperadminClientesEditarClienteIdRoute
  '/superadmin/productos/desactivar/$productId': typeof SuperadminProductosDesactivarProductIdRoute
  '/superadmin/productos/editar/$productId': typeof SuperadminProductosEditarProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRouteRouteWithChildren
  '/empleado': typeof EmpleadoRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/superadmin': typeof SuperadminRouteRouteWithChildren
  '/caja': typeof CajaRoute
  '/api/categorias': typeof ApiCategoriasRouteWithChildren
  '/api/clientes': typeof ApiClientesRouteWithChildren
  '/api/docs': typeof ApiDocsRoute
  '/api/empleados': typeof ApiEmpleadosRouteWithChildren
  '/api/productos': typeof ApiProductosRouteWithChildren
  '/api/proveedores': typeof ApiProveedoresRouteWithChildren
  '/api/ventas': typeof ApiVentasRouteWithChildren
  '/login/cliente': typeof LoginClienteRoute
  '/login/empleado': typeof LoginEmpleadoRoute
  '/tienda/compras': typeof TiendaComprasRoute
  '/analista/': typeof AnalistaIndexRoute
  '/api/': typeof ApiIndexRoute
  '/empleado/': typeof EmpleadoIndexRoute
  '/login/': typeof LoginIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categorias/$id': typeof ApiCategoriasIdRoute
  '/api/clientes/$id': typeof ApiClientesIdRoute
  '/api/clientes/me': typeof ApiClientesMeRouteWithChildren
  '/api/empleados/$userId': typeof ApiEmpleadosUserIdRoute
  '/api/productos/$id': typeof ApiProductosIdRoute
  '/api/proveedores/$id': typeof ApiProveedoresIdRoute
  '/api/reportes/clientes-frecuentes': typeof ApiReportesClientesFrecuentesRoute
  '/api/reportes/productos-mas-vendidos': typeof ApiReportesProductosMasVendidosRoute
  '/api/reportes/stock-disponible': typeof ApiReportesStockDisponibleRoute
  '/api/reportes/ventas-del-dia': typeof ApiReportesVentasDelDiaRoute
  '/api/reportes/ventas-por-categoria': typeof ApiReportesVentasPorCategoriaRoute
  '/api/setup/bootstrap': typeof ApiSetupBootstrapRoute
  '/api/setup/status': typeof ApiSetupStatusRoute
  '/api/upload/imagen': typeof ApiUploadImagenRoute
  '/api/ventas/$id': typeof ApiVentasIdRoute
  '/api/clientes/me/ventas': typeof ApiClientesMeVentasRoute
  '/empleado/clientes/editar/$clienteId': typeof EmpleadoClientesEditarClienteIdRoute
  '/empleado/productos/desactivar/$productId': typeof EmpleadoProductosDesactivarProductIdRoute
  '/empleado/productos/editar/$productId': typeof EmpleadoProductosEditarProductIdRoute
  '/portal/clientes/editar/$clienteId': typeof PortalClientesEditarClienteIdRoute
  '/portal/productos/desactivar/$productId': typeof PortalProductosDesactivarProductIdRoute
  '/portal/productos/editar/$productId': typeof PortalProductosEditarProductIdRoute
  '/superadmin/clientes/editar/$clienteId': typeof SuperadminClientesEditarClienteIdRoute
  '/superadmin/productos/desactivar/$productId': typeof SuperadminProductosDesactivarProductIdRoute
  '/superadmin/productos/editar/$productId': typeof SuperadminProductosEditarProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analista'
    | '/empleado'
    | '/login'
    | '/portal'
    | '/superadmin'
    | '/caja'
    | '/api/categorias'
    | '/api/clientes'
    | '/api/docs'
    | '/api/empleados'
    | '/api/productos'
    | '/api/proveedores'
    | '/api/ventas'
    | '/login/cliente'
    | '/login/empleado'
    | '/tienda/compras'
    | '/analista/'
    | '/api/'
    | '/empleado/'
    | '/login/'
    | '/portal/'
    | '/setup/'
    | '/superadmin/'
    | '/tienda/'
    | '/api/auth/$'
    | '/api/categorias/$id'
    | '/api/clientes/$id'
    | '/api/clientes/me'
    | '/api/empleados/$userId'
    | '/api/productos/$id'
    | '/api/proveedores/$id'
    | '/api/reportes/clientes-frecuentes'
    | '/api/reportes/productos-mas-vendidos'
    | '/api/reportes/stock-disponible'
    | '/api/reportes/ventas-del-dia'
    | '/api/reportes/ventas-por-categoria'
    | '/api/setup/bootstrap'
    | '/api/setup/status'
    | '/api/upload/imagen'
    | '/api/ventas/$id'
    | '/api/clientes/me/ventas'
    | '/empleado/clientes/editar/$clienteId'
    | '/empleado/productos/desactivar/$productId'
    | '/empleado/productos/editar/$productId'
    | '/portal/clientes/editar/$clienteId'
    | '/portal/productos/desactivar/$productId'
    | '/portal/productos/editar/$productId'
    | '/superadmin/clientes/editar/$clienteId'
    | '/superadmin/productos/desactivar/$productId'
    | '/superadmin/productos/editar/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caja'
    | '/api/categorias'
    | '/api/clientes'
    | '/api/docs'
    | '/api/empleados'
    | '/api/productos'
    | '/api/proveedores'
    | '/api/ventas'
    | '/login/cliente'
    | '/login/empleado'
    | '/tienda/compras'
    | '/analista'
    | '/api'
    | '/empleado'
    | '/login'
    | '/portal'
    | '/setup'
    | '/superadmin'
    | '/tienda'
    | '/api/auth/$'
    | '/api/categorias/$id'
    | '/api/clientes/$id'
    | '/api/clientes/me'
    | '/api/empleados/$userId'
    | '/api/productos/$id'
    | '/api/proveedores/$id'
    | '/api/reportes/clientes-frecuentes'
    | '/api/reportes/productos-mas-vendidos'
    | '/api/reportes/stock-disponible'
    | '/api/reportes/ventas-del-dia'
    | '/api/reportes/ventas-por-categoria'
    | '/api/setup/bootstrap'
    | '/api/setup/status'
    | '/api/upload/imagen'
    | '/api/ventas/$id'
    | '/api/clientes/me/ventas'
    | '/empleado/clientes/editar/$clienteId'
    | '/empleado/productos/desactivar/$productId'
    | '/empleado/productos/editar/$productId'
    | '/portal/clientes/editar/$clienteId'
    | '/portal/productos/desactivar/$productId'
    | '/portal/productos/editar/$productId'
    | '/superadmin/clientes/editar/$clienteId'
    | '/superadmin/productos/desactivar/$productId'
    | '/superadmin/productos/editar/$productId'
  id:
    | '__root__'
    | '/'
    | '/analista'
    | '/empleado'
    | '/login'
    | '/portal'
    | '/superadmin'
    | '/caja'
    | '/api/categorias'
    | '/api/clientes'
    | '/api/docs'
    | '/api/empleados'
    | '/api/productos'
    | '/api/proveedores'
    | '/api/ventas'
    | '/login/cliente'
    | '/login/empleado'
    | '/tienda/compras'
    | '/analista/'
    | '/api/'
    | '/empleado/'
    | '/login/'
    | '/portal/'
    | '/setup/'
    | '/superadmin/'
    | '/tienda/'
    | '/api/auth/$'
    | '/api/categorias/$id'
    | '/api/clientes/$id'
    | '/api/clientes/me'
    | '/api/empleados/$userId'
    | '/api/productos/$id'
    | '/api/proveedores/$id'
    | '/api/reportes/clientes-frecuentes'
    | '/api/reportes/productos-mas-vendidos'
    | '/api/reportes/stock-disponible'
    | '/api/reportes/ventas-del-dia'
    | '/api/reportes/ventas-por-categoria'
    | '/api/setup/bootstrap'
    | '/api/setup/status'
    | '/api/upload/imagen'
    | '/api/ventas/$id'
    | '/api/clientes/me/ventas'
    | '/empleado/clientes/editar/$clienteId'
    | '/empleado/productos/desactivar/$productId'
    | '/empleado/productos/editar/$productId'
    | '/portal/clientes/editar/$clienteId'
    | '/portal/productos/desactivar/$productId'
    | '/portal/productos/editar/$productId'
    | '/superadmin/clientes/editar/$clienteId'
    | '/superadmin/productos/desactivar/$productId'
    | '/superadmin/productos/editar/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistaRouteRoute: typeof AnalistaRouteRouteWithChildren
  EmpleadoRouteRoute: typeof EmpleadoRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  SuperadminRouteRoute: typeof SuperadminRouteRouteWithChildren
  CajaRoute: typeof CajaRoute
  ApiCategoriasRoute: typeof ApiCategoriasRouteWithChildren
  ApiClientesRoute: typeof ApiClientesRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  ApiEmpleadosRoute: typeof ApiEmpleadosRouteWithChildren
  ApiProductosRoute: typeof ApiProductosRouteWithChildren
  ApiProveedoresRoute: typeof ApiProveedoresRouteWithChildren
  ApiVentasRoute: typeof ApiVentasRouteWithChildren
  TiendaComprasRoute: typeof TiendaComprasRoute
  ApiIndexRoute: typeof ApiIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiReportesClientesFrecuentesRoute: typeof ApiReportesClientesFrecuentesRoute
  ApiReportesProductosMasVendidosRoute: typeof ApiReportesProductosMasVendidosRoute
  ApiReportesStockDisponibleRoute: typeof ApiReportesStockDisponibleRoute
  ApiReportesVentasDelDiaRoute: typeof ApiReportesVentasDelDiaRoute
  ApiReportesVentasPorCategoriaRoute: typeof ApiReportesVentasPorCategoriaRoute
  ApiSetupBootstrapRoute: typeof ApiSetupBootstrapRoute
  ApiSetupStatusRoute: typeof ApiSetupStatusRoute
  ApiUploadImagenRoute: typeof ApiUploadImagenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleado': {
      id: '/empleado'
      path: '/empleado'
      fullPath: '/empleado'
      preLoaderRoute: typeof EmpleadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista': {
      id: '/analista'
      path: '/analista'
      fullPath: '/analista'
      preLoaderRoute: typeof AnalistaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/tienda'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/empleado/': {
      id: '/empleado/'
      path: '/'
      fullPath: '/empleado/'
      preLoaderRoute: typeof EmpleadoIndexRouteImport
      parentRoute: typeof EmpleadoRouteRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista/': {
      id: '/analista/'
      path: '/'
      fullPath: '/analista/'
      preLoaderRoute: typeof AnalistaIndexRouteImport
      parentRoute: typeof AnalistaRouteRoute
    }
    '/tienda/compras': {
      id: '/tienda/compras'
      path: '/tienda/compras'
      fullPath: '/tienda/compras'
      preLoaderRoute: typeof TiendaComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/empleado': {
      id: '/login/empleado'
      path: '/empleado'
      fullPath: '/login/empleado'
      preLoaderRoute: typeof LoginEmpleadoRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/cliente': {
      id: '/login/cliente'
      path: '/cliente'
      fullPath: '/login/cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/api/ventas': {
      id: '/api/ventas'
      path: '/api/ventas'
      fullPath: '/api/ventas'
      preLoaderRoute: typeof ApiVentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proveedores': {
      id: '/api/proveedores'
      path: '/api/proveedores'
      fullPath: '/api/proveedores'
      preLoaderRoute: typeof ApiProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/productos': {
      id: '/api/productos'
      path: '/api/productos'
      fullPath: '/api/productos'
      preLoaderRoute: typeof ApiProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/empleados': {
      id: '/api/empleados'
      path: '/api/empleados'
      fullPath: '/api/empleados'
      preLoaderRoute: typeof ApiEmpleadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clientes': {
      id: '/api/clientes'
      path: '/api/clientes'
      fullPath: '/api/clientes'
      preLoaderRoute: typeof ApiClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categorias': {
      id: '/api/categorias'
      path: '/api/categorias'
      fullPath: '/api/categorias'
      preLoaderRoute: typeof ApiCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ventas/$id': {
      id: '/api/ventas/$id'
      path: '/$id'
      fullPath: '/api/ventas/$id'
      preLoaderRoute: typeof ApiVentasIdRouteImport
      parentRoute: typeof ApiVentasRoute
    }
    '/api/upload/imagen': {
      id: '/api/upload/imagen'
      path: '/api/upload/imagen'
      fullPath: '/api/upload/imagen'
      preLoaderRoute: typeof ApiUploadImagenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup/status': {
      id: '/api/setup/status'
      path: '/api/setup/status'
      fullPath: '/api/setup/status'
      preLoaderRoute: typeof ApiSetupStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/setup/bootstrap': {
      id: '/api/setup/bootstrap'
      path: '/api/setup/bootstrap'
      fullPath: '/api/setup/bootstrap'
      preLoaderRoute: typeof ApiSetupBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reportes/ventas-por-categoria': {
      id: '/api/reportes/ventas-por-categoria'
      path: '/api/reportes/ventas-por-categoria'
      fullPath: '/api/reportes/ventas-por-categoria'
      preLoaderRoute: typeof ApiReportesVentasPorCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reportes/ventas-del-dia': {
      id: '/api/reportes/ventas-del-dia'
      path: '/api/reportes/ventas-del-dia'
      fullPath: '/api/reportes/ventas-del-dia'
      preLoaderRoute: typeof ApiReportesVentasDelDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reportes/stock-disponible': {
      id: '/api/reportes/stock-disponible'
      path: '/api/reportes/stock-disponible'
      fullPath: '/api/reportes/stock-disponible'
      preLoaderRoute: typeof ApiReportesStockDisponibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reportes/productos-mas-vendidos': {
      id: '/api/reportes/productos-mas-vendidos'
      path: '/api/reportes/productos-mas-vendidos'
      fullPath: '/api/reportes/productos-mas-vendidos'
      preLoaderRoute: typeof ApiReportesProductosMasVendidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reportes/clientes-frecuentes': {
      id: '/api/reportes/clientes-frecuentes'
      path: '/api/reportes/clientes-frecuentes'
      fullPath: '/api/reportes/clientes-frecuentes'
      preLoaderRoute: typeof ApiReportesClientesFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proveedores/$id': {
      id: '/api/proveedores/$id'
      path: '/$id'
      fullPath: '/api/proveedores/$id'
      preLoaderRoute: typeof ApiProveedoresIdRouteImport
      parentRoute: typeof ApiProveedoresRoute
    }
    '/api/productos/$id': {
      id: '/api/productos/$id'
      path: '/$id'
      fullPath: '/api/productos/$id'
      preLoaderRoute: typeof ApiProductosIdRouteImport
      parentRoute: typeof ApiProductosRoute
    }
    '/api/empleados/$userId': {
      id: '/api/empleados/$userId'
      path: '/$userId'
      fullPath: '/api/empleados/$userId'
      preLoaderRoute: typeof ApiEmpleadosUserIdRouteImport
      parentRoute: typeof ApiEmpleadosRoute
    }
    '/api/clientes/me': {
      id: '/api/clientes/me'
      path: '/me'
      fullPath: '/api/clientes/me'
      preLoaderRoute: typeof ApiClientesMeRouteImport
      parentRoute: typeof ApiClientesRoute
    }
    '/api/clientes/$id': {
      id: '/api/clientes/$id'
      path: '/$id'
      fullPath: '/api/clientes/$id'
      preLoaderRoute: typeof ApiClientesIdRouteImport
      parentRoute: typeof ApiClientesRoute
    }
    '/api/categorias/$id': {
      id: '/api/categorias/$id'
      path: '/$id'
      fullPath: '/api/categorias/$id'
      preLoaderRoute: typeof ApiCategoriasIdRouteImport
      parentRoute: typeof ApiCategoriasRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/productos/editar/$productId': {
      id: '/superadmin/productos/editar/$productId'
      path: '/productos/editar/$productId'
      fullPath: '/superadmin/productos/editar/$productId'
      preLoaderRoute: typeof SuperadminProductosEditarProductIdRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/productos/desactivar/$productId': {
      id: '/superadmin/productos/desactivar/$productId'
      path: '/productos/desactivar/$productId'
      fullPath: '/superadmin/productos/desactivar/$productId'
      preLoaderRoute: typeof SuperadminProductosDesactivarProductIdRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/superadmin/clientes/editar/$clienteId': {
      id: '/superadmin/clientes/editar/$clienteId'
      path: '/clientes/editar/$clienteId'
      fullPath: '/superadmin/clientes/editar/$clienteId'
      preLoaderRoute: typeof SuperadminClientesEditarClienteIdRouteImport
      parentRoute: typeof SuperadminRouteRoute
    }
    '/portal/productos/editar/$productId': {
      id: '/portal/productos/editar/$productId'
      path: '/productos/editar/$productId'
      fullPath: '/portal/productos/editar/$productId'
      preLoaderRoute: typeof PortalProductosEditarProductIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/productos/desactivar/$productId': {
      id: '/portal/productos/desactivar/$productId'
      path: '/productos/desactivar/$productId'
      fullPath: '/portal/productos/desactivar/$productId'
      preLoaderRoute: typeof PortalProductosDesactivarProductIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/clientes/editar/$clienteId': {
      id: '/portal/clientes/editar/$clienteId'
      path: '/clientes/editar/$clienteId'
      fullPath: '/portal/clientes/editar/$clienteId'
      preLoaderRoute: typeof PortalClientesEditarClienteIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/empleado/productos/editar/$productId': {
      id: '/empleado/productos/editar/$productId'
      path: '/productos/editar/$productId'
      fullPath: '/empleado/productos/editar/$productId'
      preLoaderRoute: typeof EmpleadoProductosEditarProductIdRouteImport
      parentRoute: typeof EmpleadoRouteRoute
    }
    '/empleado/productos/desactivar/$productId': {
      id: '/empleado/productos/desactivar/$productId'
      path: '/productos/desactivar/$productId'
      fullPath: '/empleado/productos/desactivar/$productId'
      preLoaderRoute: typeof EmpleadoProductosDesactivarProductIdRouteImport
      parentRoute: typeof EmpleadoRouteRoute
    }
    '/empleado/clientes/editar/$clienteId': {
      id: '/empleado/clientes/editar/$clienteId'
      path: '/clientes/editar/$clienteId'
      fullPath: '/empleado/clientes/editar/$clienteId'
      preLoaderRoute: typeof EmpleadoClientesEditarClienteIdRouteImport
      parentRoute: typeof EmpleadoRouteRoute
    }
    '/api/clientes/me/ventas': {
      id: '/api/clientes/me/ventas'
      path: '/ventas'
      fullPath: '/api/clientes/me/ventas'
      preLoaderRoute: typeof ApiClientesMeVentasRouteImport
      parentRoute: typeof ApiClientesMeRoute
    }
  }
}

interface AnalistaRouteRouteChildren {
  AnalistaIndexRoute: typeof AnalistaIndexRoute
}

const AnalistaRouteRouteChildren: AnalistaRouteRouteChildren = {
  AnalistaIndexRoute: AnalistaIndexRoute,
}

const AnalistaRouteRouteWithChildren = AnalistaRouteRoute._addFileChildren(
  AnalistaRouteRouteChildren,
)

interface EmpleadoRouteRouteChildren {
  EmpleadoIndexRoute: typeof EmpleadoIndexRoute
  EmpleadoClientesEditarClienteIdRoute: typeof EmpleadoClientesEditarClienteIdRoute
  EmpleadoProductosDesactivarProductIdRoute: typeof EmpleadoProductosDesactivarProductIdRoute
  EmpleadoProductosEditarProductIdRoute: typeof EmpleadoProductosEditarProductIdRoute
}

const EmpleadoRouteRouteChildren: EmpleadoRouteRouteChildren = {
  EmpleadoIndexRoute: EmpleadoIndexRoute,
  EmpleadoClientesEditarClienteIdRoute: EmpleadoClientesEditarClienteIdRoute,
  EmpleadoProductosDesactivarProductIdRoute:
    EmpleadoProductosDesactivarProductIdRoute,
  EmpleadoProductosEditarProductIdRoute: EmpleadoProductosEditarProductIdRoute,
}

const EmpleadoRouteRouteWithChildren = EmpleadoRouteRoute._addFileChildren(
  EmpleadoRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginClienteRoute: typeof LoginClienteRoute
  LoginEmpleadoRoute: typeof LoginEmpleadoRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginClienteRoute: LoginClienteRoute,
  LoginEmpleadoRoute: LoginEmpleadoRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalClientesEditarClienteIdRoute: typeof PortalClientesEditarClienteIdRoute
  PortalProductosDesactivarProductIdRoute: typeof PortalProductosDesactivarProductIdRoute
  PortalProductosEditarProductIdRoute: typeof PortalProductosEditarProductIdRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalClientesEditarClienteIdRoute: PortalClientesEditarClienteIdRoute,
  PortalProductosDesactivarProductIdRoute:
    PortalProductosDesactivarProductIdRoute,
  PortalProductosEditarProductIdRoute: PortalProductosEditarProductIdRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface SuperadminRouteRouteChildren {
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminClientesEditarClienteIdRoute: typeof SuperadminClientesEditarClienteIdRoute
  SuperadminProductosDesactivarProductIdRoute: typeof SuperadminProductosDesactivarProductIdRoute
  SuperadminProductosEditarProductIdRoute: typeof SuperadminProductosEditarProductIdRoute
}

const SuperadminRouteRouteChildren: SuperadminRouteRouteChildren = {
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminClientesEditarClienteIdRoute:
    SuperadminClientesEditarClienteIdRoute,
  SuperadminProductosDesactivarProductIdRoute:
    SuperadminProductosDesactivarProductIdRoute,
  SuperadminProductosEditarProductIdRoute:
    SuperadminProductosEditarProductIdRoute,
}

const SuperadminRouteRouteWithChildren = SuperadminRouteRoute._addFileChildren(
  SuperadminRouteRouteChildren,
)

interface ApiCategoriasRouteChildren {
  ApiCategoriasIdRoute: typeof ApiCategoriasIdRoute
}

const ApiCategoriasRouteChildren: ApiCategoriasRouteChildren = {
  ApiCategoriasIdRoute: ApiCategoriasIdRoute,
}

const ApiCategoriasRouteWithChildren = ApiCategoriasRoute._addFileChildren(
  ApiCategoriasRouteChildren,
)

interface ApiClientesMeRouteChildren {
  ApiClientesMeVentasRoute: typeof ApiClientesMeVentasRoute
}

const ApiClientesMeRouteChildren: ApiClientesMeRouteChildren = {
  ApiClientesMeVentasRoute: ApiClientesMeVentasRoute,
}

const ApiClientesMeRouteWithChildren = ApiClientesMeRoute._addFileChildren(
  ApiClientesMeRouteChildren,
)

interface ApiClientesRouteChildren {
  ApiClientesIdRoute: typeof ApiClientesIdRoute
  ApiClientesMeRoute: typeof ApiClientesMeRouteWithChildren
}

const ApiClientesRouteChildren: ApiClientesRouteChildren = {
  ApiClientesIdRoute: ApiClientesIdRoute,
  ApiClientesMeRoute: ApiClientesMeRouteWithChildren,
}

const ApiClientesRouteWithChildren = ApiClientesRoute._addFileChildren(
  ApiClientesRouteChildren,
)

interface ApiEmpleadosRouteChildren {
  ApiEmpleadosUserIdRoute: typeof ApiEmpleadosUserIdRoute
}

const ApiEmpleadosRouteChildren: ApiEmpleadosRouteChildren = {
  ApiEmpleadosUserIdRoute: ApiEmpleadosUserIdRoute,
}

const ApiEmpleadosRouteWithChildren = ApiEmpleadosRoute._addFileChildren(
  ApiEmpleadosRouteChildren,
)

interface ApiProductosRouteChildren {
  ApiProductosIdRoute: typeof ApiProductosIdRoute
}

const ApiProductosRouteChildren: ApiProductosRouteChildren = {
  ApiProductosIdRoute: ApiProductosIdRoute,
}

const ApiProductosRouteWithChildren = ApiProductosRoute._addFileChildren(
  ApiProductosRouteChildren,
)

interface ApiProveedoresRouteChildren {
  ApiProveedoresIdRoute: typeof ApiProveedoresIdRoute
}

const ApiProveedoresRouteChildren: ApiProveedoresRouteChildren = {
  ApiProveedoresIdRoute: ApiProveedoresIdRoute,
}

const ApiProveedoresRouteWithChildren = ApiProveedoresRoute._addFileChildren(
  ApiProveedoresRouteChildren,
)

interface ApiVentasRouteChildren {
  ApiVentasIdRoute: typeof ApiVentasIdRoute
}

const ApiVentasRouteChildren: ApiVentasRouteChildren = {
  ApiVentasIdRoute: ApiVentasIdRoute,
}

const ApiVentasRouteWithChildren = ApiVentasRoute._addFileChildren(
  ApiVentasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistaRouteRoute: AnalistaRouteRouteWithChildren,
  EmpleadoRouteRoute: EmpleadoRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  SuperadminRouteRoute: SuperadminRouteRouteWithChildren,
  CajaRoute: CajaRoute,
  ApiCategoriasRoute: ApiCategoriasRouteWithChildren,
  ApiClientesRoute: ApiClientesRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  ApiEmpleadosRoute: ApiEmpleadosRouteWithChildren,
  ApiProductosRoute: ApiProductosRouteWithChildren,
  ApiProveedoresRoute: ApiProveedoresRouteWithChildren,
  ApiVentasRoute: ApiVentasRouteWithChildren,
  TiendaComprasRoute: TiendaComprasRoute,
  ApiIndexRoute: ApiIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  TiendaIndexRoute: TiendaIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiReportesClientesFrecuentesRoute: ApiReportesClientesFrecuentesRoute,
  ApiReportesProductosMasVendidosRoute: ApiReportesProductosMasVendidosRoute,
  ApiReportesStockDisponibleRoute: ApiReportesStockDisponibleRoute,
  ApiReportesVentasDelDiaRoute: ApiReportesVentasDelDiaRoute,
  ApiReportesVentasPorCategoriaRoute: ApiReportesVentasPorCategoriaRoute,
  ApiSetupBootstrapRoute: ApiSetupBootstrapRoute,
  ApiSetupStatusRoute: ApiSetupStatusRoute,
  ApiUploadImagenRoute: ApiUploadImagenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
